<?php

return [
    'gpt-4o' => ['description' => 'OpenAI 多模态旗舰模型，支持文本、图像理解与工具调用。', 'tags' => 'OpenAI,多模态,旗舰'],
    'gpt-4o-mini' => ['description' => 'OpenAI 轻量多模态模型，适合高并发和低成本场景。', 'tags' => 'OpenAI,多模态,轻量'],
    'gpt-4.1' => ['description' => 'OpenAI 新一代通用模型，擅长复杂推理、代码和长上下文任务。', 'tags' => 'OpenAI,推理,代码'],
    'gpt-4.1-mini' => ['description' => 'OpenAI 新一代轻量通用模型，兼顾速度、效果和成本。', 'tags' => 'OpenAI,轻量,通用'],
    'gpt-4.1-nano' => ['description' => 'OpenAI 超轻量模型，适合分类、抽取和高吞吐任务。', 'tags' => 'OpenAI,轻量,高吞吐'],
    'o1' => ['description' => 'OpenAI 推理模型，适合数学、科学和复杂分析任务。', 'tags' => 'OpenAI,推理'],
    'o3' => ['description' => 'OpenAI 高级推理模型，适合复杂问题求解和代码任务。', 'tags' => 'OpenAI,推理,代码'],
    'o3-mini' => ['description' => 'OpenAI 高性价比推理模型，适合代码和数学任务。', 'tags' => 'OpenAI,推理,轻量'],
    'claude-3-5-sonnet' => ['description' => 'Anthropic 高性能通用模型，擅长写作、分析、代码和视觉理解。', 'tags' => 'Anthropic,Claude,多模态'],
    'claude-3-7-sonnet' => ['description' => 'Anthropic 推理增强模型，支持深度思考和复杂代码任务。', 'tags' => 'Anthropic,Claude,推理'],
    'claude-sonnet-4' => ['description' => 'Anthropic 新一代均衡模型，兼具强推理、代码和长上下文能力。', 'tags' => 'Anthropic,Claude,推理'],
    'claude-opus-4' => ['description' => 'Anthropic 高端模型，面向最复杂的推理、研究和软件工程任务。', 'tags' => 'Anthropic,Claude,旗舰'],
    'claude-3-5-haiku' => ['description' => 'Anthropic 快速轻量模型，适合高并发和低延迟应用。', 'tags' => 'Anthropic,Claude,轻量'],
    'gemini-2.5-pro' => ['description' => 'Google Gemini 高级多模态推理模型，支持长上下文。', 'tags' => 'Google,Gemini,多模态,推理'],
    'gemini-2.5-flash' => ['description' => 'Google Gemini 快速高性价比多模态模型。', 'tags' => 'Google,Gemini,多模态,快速'],
    'gemini-2.0-flash' => ['description' => 'Google Gemini 快速多模态模型，适合通用对话和工具调用。', 'tags' => 'Google,Gemini,多模态'],
    'deepseek-chat' => ['description' => 'DeepSeek 通用对话模型，适合中文、代码和知识问答。', 'tags' => 'DeepSeek,中文,通用'],
    'deepseek-reasoner' => ['description' => 'DeepSeek 深度推理模型，适合数学、逻辑和复杂代码任务。', 'tags' => 'DeepSeek,中文,推理'],
    'qwen-max' => ['description' => '阿里通义千问旗舰通用模型，适合复杂中文任务和企业应用。', 'tags' => '阿里云,Qwen,中文,旗舰'],
    'qwen-plus' => ['description' => '阿里通义千问均衡模型，兼顾效果、速度和成本。', 'tags' => '阿里云,Qwen,中文'],
    'qwen-turbo' => ['description' => '阿里通义千问快速模型，适合高并发和低延迟场景。', 'tags' => '阿里云,Qwen,快速'],
    'qwen2.5-72b-instruct' => ['description' => '通义千问开源大语言模型，具备较强中文、代码和指令遵循能力。', 'tags' => 'Qwen,开源,中文,代码'],
    'qwen2.5-coder-32b-instruct' => ['description' => '通义千问代码模型，专注代码生成、补全和调试。', 'tags' => 'Qwen,开源,代码'],
    'glm-4-plus' => ['description' => '智谱 GLM 系列高级通用模型，适合中文对话和复杂任务。', 'tags' => '智谱,GLM,中文'],
    'glm-4-flash' => ['description' => '智谱 GLM 快速轻量模型，适合低成本高并发场景。', 'tags' => '智谱,GLM,快速'],
    'glm-4.5' => ['description' => '智谱新一代通用推理模型，兼顾代码、推理和中文能力。', 'tags' => '智谱,GLM,推理'],
    'moonshot-v1-8k' => ['description' => 'Moonshot/Kimi 长文本模型，支持 8K 上下文。', 'tags' => 'Moonshot,Kimi,长文本'],
    'moonshot-v1-32k' => ['description' => 'Moonshot/Kimi 长文本模型，支持 32K 上下文。', 'tags' => 'Moonshot,Kimi,长文本'],
    'kimi-k2' => ['description' => 'Kimi 开源通用模型，适合中文、代码和工具调用任务。', 'tags' => 'Moonshot,Kimi,开源,代码'],
    'mistral-large-latest' => ['description' => 'Mistral 高性能通用模型，适合多语言和复杂推理。', 'tags' => 'Mistral,多语言'],
    'mistral-small-latest' => ['description' => 'Mistral 轻量高性价比模型，适合常规对话和抽取任务。', 'tags' => 'Mistral,轻量'],
    'codestral-latest' => ['description' => 'Mistral 代码专用模型，适合代码生成和补全。', 'tags' => 'Mistral,代码'],
    'llama-3.3-70b-versatile' => ['description' => 'Meta Llama 开源通用模型，适合多语言对话和推理。', 'tags' => 'Meta,Llama,开源'],
    'llama-4-scout' => ['description' => 'Meta Llama 多模态模型，面向高效视觉和文本理解。', 'tags' => 'Meta,Llama,多模态,开源'],
    'llama-4-maverick' => ['description' => 'Meta Llama 高性能多模态模型，适合复杂通用任务。', 'tags' => 'Meta,Llama,多模态,开源'],
    'command-r-plus' => ['description' => 'Cohere 企业级检索增强和工具调用模型。', 'tags' => 'Cohere,RAG,企业'],
    'command-a' => ['description' => 'Cohere 高效通用模型，适合企业文本和工具调用场景。', 'tags' => 'Cohere,企业'],
    'grok-3' => ['description' => 'xAI Grok 通用推理模型，适合对话、分析和代码任务。', 'tags' => 'xAI,Grok,推理'],
    'grok-3-mini' => ['description' => 'xAI Grok 轻量推理模型，适合快速分析和代码任务。', 'tags' => 'xAI,Grok,轻量'],
    'doubao-seed-1.6' => ['description' => '字节豆包通用模型，支持中文对话、推理和多模态能力。', 'tags' => '豆包,中文,多模态'],
    'hunyuan-turbo' => ['description' => '腾讯混元快速通用模型，适合中文对话和企业场景。', 'tags' => '腾讯,混元,中文'],
    'yi-large' => ['description' => '零一万物通用大模型，适合中文和多语言任务。', 'tags' => '零一万物,Yi,中文'],
    'step-2-16k' => ['description' => '阶跃星辰通用模型，适合中文对话和复杂任务。', 'tags' => '阶跃星辰,中文'],
];
